"""
CV-Craft-Studio - LaTeX Resume Exporter
Generates an ATS-friendly LaTeX CV in the compact academic/engineering format.
No external APIs are used.
"""

from datetime import datetime
from typing import Any, Dict, Iterable, List
import re

NL = r"\\"


def _latex_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _clean_list(values: Any) -> List[str]:
    if not values:
        return []
    if isinstance(values, str):
        return [p.strip() for p in re.split(r"[,\n;|]+", values) if p.strip()]
    if isinstance(values, dict):
        out: List[str] = []
        for v in values.values():
            out.extend(_clean_list(v))
        return out
    if isinstance(values, Iterable):
        return [str(v).strip() for v in values if str(v).strip()]
    return [str(values).strip()]


def _raw_lines(text: str, max_lines: int = 10) -> List[str]:
    lines = []
    for line in (text or "").splitlines():
        cleaned = re.sub(r"^[\s•\-*–—\d\.)]+", "", line).strip()
        if cleaned:
            lines.append(cleaned)
    return lines[:max_lines]


def _latex_item(text: str) -> str:
    return f"        \\item {{{_latex_escape(text)}}}"


def _safe_name(resume_data: Dict) -> str:
    name = resume_data.get("personal", {}).get("name", "Updated_CV") or "Updated_CV"
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_") or "Updated_CV"


def get_latex_filename(resume_data: Dict) -> str:
    return f"{_safe_name(resume_data)}_ATS_Optimized_CV_{datetime.now().strftime('%Y%m%d')}.tex"


def _preamble() -> List[str]:
    return [
        "%-------------------------",
        "% ATS-Optimized Resume in LaTeX",
        "% Generated by CV-Craft-Studio",
        "%------------------------",
        r"\documentclass[a4paper,11pt]{article}",
        r"\usepackage{latexsym}",
        r"\usepackage{xcolor}",
        r"\usepackage{float}",
        r"\usepackage{ragged2e}",
        r"\usepackage[empty]{fullpage}",
        r"\usepackage{wrapfig}",
        r"\usepackage{tabularx}",
        r"\usepackage{titlesec}",
        r"\usepackage{geometry}",
        r"\usepackage{marvosym}",
        r"\usepackage{verbatim}",
        r"\usepackage{enumitem}",
        r"\usepackage[hidelinks]{hyperref}",
        r"\usepackage{fancyhdr}",
        r"\usepackage{fontawesome5}",
        r"\usepackage{multicol}",
        r"\usepackage{graphicx}",
        r"\usepackage{cfr-lm}",
        r"\usepackage[T1]{fontenc}",
        r"\setlength{\multicolsep}{0pt}",
        r"\pagestyle{fancy}",
        r"\fancyhf{}",
        r"\fancyfoot{}",
        r"\renewcommand{\headrulewidth}{0pt}",
        r"\renewcommand{\footrulewidth}{0pt}",
        r"\geometry{left=1.4cm, top=0.8cm, right=1.2cm, bottom=1cm}",
        r"\usepackage[most]{tcolorbox}",
        r"\tcbset{frame code={},center title,left=0pt,right=0pt,top=0pt,bottom=0pt,colback=gray!20,colframe=white,width=\dimexpr\textwidth\relax,enlarge left by=-2mm,boxsep=4pt,arc=0pt,outer arc=0pt,}",
        r"\urlstyle{same}",
        r"\raggedright",
        r"\setlength{\tabcolsep}{0in}",
        r"\titleformat{\section}{\vspace{-4pt}\scshape\raggedright\large}{}{0em}{}[\color{black}\titlerule \vspace{-7pt}]",
        r"\newcommand{\resumeItem}[2]{\item{\textbf{#1}{\hspace{0.5mm}#2 \vspace{-0.5mm}}}}",
        r"\newcommand{\resumePOR}[3]{\vspace{0.5mm}\item\begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}\textbf{#1}\hspace{0.3mm}#2 & \textit{\small{#3}} \end{tabular*}\vspace{-2mm}}",
        r"\newcommand{\resumeSubheading}[4]{\vspace{0.5mm}\item\begin{tabular*}{0.98\textwidth}[t]{l@{\extracolsep{\fill}}r}\textbf{#1} & \textit{\footnotesize{#4}} \\ \textit{\footnotesize{#3}} & \footnotesize{#2}\\\end{tabular*}\vspace{-2.4mm}}",
        r"\newcommand{\resumeProject}[4]{\vspace{0.5mm}\item\begin{tabular*}{0.98\textwidth}[t]{l@{\extracolsep{\fill}}r}\textbf{#1} & \textit{\footnotesize{#3}} \\ \footnotesize{\textit{#2}} & \footnotesize{#4}\end{tabular*}\vspace{-2.4mm}}",
        r"\newcommand{\resumeSubItem}[2]{\resumeItem{#1}{#2}\vspace{-4pt}}",
        r"\renewcommand{\labelitemi}{$\vcenter{\hbox{\tiny$\bullet$}}$}",
        r"\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=*,labelsep=0mm]}",
        r"\newcommand{\resumeHeadingSkillStart}{\begin{itemize}[leftmargin=*,itemsep=1.7mm, rightmargin=2ex]}",
        r"\newcommand{\resumeItemListStart}{\begin{justify}\begin{itemize}[leftmargin=3ex, rightmargin=2ex, noitemsep,labelsep=1.2mm,itemsep=0mm]\small}",
        r"\newcommand{\resumeSubHeadingListEnd}{\end{itemize}\vspace{2mm}}",
        r"\newcommand{\resumeHeadingSkillEnd}{\end{itemize}\vspace{-2mm}}",
        r"\newcommand{\resumeItemListEnd}{\end{itemize}\end{justify}\vspace{-2mm}}",
        r"\newcolumntype{L}{>{\raggedright\arraybackslash}X}%",
        r"\newcolumntype{R}{>{\raggedleft\arraybackslash}X}%",
        r"\newcolumntype{C}{>{\centering\arraybackslash}X}%",
    ]


def export_latex_resume(resume_data: Dict) -> bytes:
    p = resume_data.get("personal", {}) or {}
    education = resume_data.get("education", []) or []
    experience = resume_data.get("experience", []) or []
    internships = resume_data.get("internships", []) or []
    projects = resume_data.get("projects", []) or []
    certifications = resume_data.get("certifications", []) or []
    achievements = resume_data.get("achievements", []) or []
    publications = resume_data.get("publications", []) or []
    skills = resume_data.get("skills", {}) or {}

    first_edu = education[0] if education else {}
    name = _latex_escape(p.get("name", "Your Name"))
    raw_phone = str(p.get("phone", "") or "")
    phone = _latex_escape(raw_phone)
    phone_prefix = "" if raw_phone.strip().startswith("+") else "+91-"
    email = _latex_escape(p.get("email", ""))
    course = _latex_escape(first_edu.get("degree", "Professional Resume"))
    institution = _latex_escape(first_edu.get("institution", p.get("location", "")))
    linkedin = (p.get("linkedin", "") or "").replace("https://", "").replace("http://", "")
    github = (p.get("github", "") or "").replace("https://", "").replace("http://", "")

    lines: List[str] = _preamble()
    lines.extend([
        f"\\newcommand{{\\name}}{{{name}}}",
        f"\\newcommand{{\\course}}{{{course}}}",
        f"\\newcommand{{\\phone}}{{{phone}}}",
        f"\\newcommand{{\\emaila}}{{{email}}}",
        r"\begin{document}",
        r"\fontfamily{cmr}\selectfont",
        r"{",
        "\\begin{tabularx}{\\linewidth}{L r} " + NL,
        f"  \\textbf{{\\Large \\name}} & {{\\raisebox{{0.0\\height}}{{\\footnotesize \\faPhone}}\\ {phone_prefix}\\phone}}" + NL,
        f"  {{{course}}} & \\href{{mailto:{email}}}{{\\raisebox{{0.0\\height}}{{\\footnotesize \\faEnvelope}}\\ {{{email}}}}} " + NL,
        f"  {{{institution}}} & " + (f"\\href{{https://{_latex_escape(github)}}}{{\\raisebox{{0.0\\height}}{{\\footnotesize \\faGithub}}\\ {{GitHub Profile}}}} " + NL if github else "{} " + NL),
        "  {} & " + (f"\\href{{https://{_latex_escape(linkedin)}}}{{\\raisebox{{0.0\\height}}{{\\footnotesize \\faLinkedin}}\\ {{LinkedIn Profile}}}}" if linkedin else "{}"),
        r"\end{tabularx}",
        r"}",
        "",
    ])

    if resume_data.get("summary"):
        lines.extend([r"\section{\textbf{Professional Summary}}", _latex_escape(resume_data["summary"]), r"\vspace{-2mm}", ""])

    if education or resume_data.get("_raw_education"):
        lines.extend([r"\section{\textbf{Education}}", r"\resumeSubHeadingListStart"])
        if education:
            for edu in education:
                lines.append(r"    \resumeSubheading")
                lines.append(f"      {{{_latex_escape(edu.get('degree', 'Degree'))}}}{{{_latex_escape(edu.get('grade', ''))}}}")
                lines.append(f"      {{{_latex_escape(edu.get('institution', 'Institution'))}}}{{{_latex_escape(edu.get('year', ''))}}}")
        else:
            raw = " ".join(_raw_lines(resume_data.get("_raw_education", ""), 4))
            lines.extend([r"    \resumeSubheading", f"      {{{_latex_escape(raw or 'Education details')}}}{{}}", r"      {}{}"])
        lines.extend([r"\resumeSubHeadingListEnd", r"\vspace{-5.5mm}", ""])

    if projects or resume_data.get("_raw_projects"):
        lines.extend([r"\section{\textbf{Personal Projects}}", r"\resumeSubHeadingListStart"])
        entries = projects or [{"title": "Key Project", "tech": "", "year": "", "bullets": _raw_lines(resume_data.get("_raw_projects", ""), 6)}]
        for proj in entries:
            lines.extend([r"    \resumeProject", f"      {{{_latex_escape(proj.get('title', 'Project'))}}}", f"      {{{_latex_escape(proj.get('tech', ''))}}}", f"      {{{_latex_escape(proj.get('year', ''))}}}", r"      {}"])
            if proj.get("bullets"):
                lines.append(r"      \resumeItemListStart")
                lines.extend(_latex_item(b) for b in proj.get("bullets", []))
                lines.append(r"      \resumeItemListEnd")
        lines.extend([r"\resumeSubHeadingListEnd", r"\vspace{-8.5mm}", ""])

    if experience or resume_data.get("_raw_experience"):
        lines.extend([r"\section{\textbf{Experience}}", r"\resumeSubHeadingListStart"])
        entries = experience or [{"title": "Professional Experience", "company": "", "duration": "", "location": "", "bullets": _raw_lines(resume_data.get("_raw_experience", ""), 6)}]
        for exp in entries:
            lines.extend([r"    \resumeSubheading", f"      {{{_latex_escape(exp.get('title', 'Role'))}}}{{{_latex_escape(exp.get('location', ''))}}}", f"      {{{_latex_escape(exp.get('company', 'Organization'))}}}{{{_latex_escape(exp.get('duration', ''))}}}"])
            if exp.get("bullets"):
                lines.append(r"      \resumeItemListStart")
                lines.extend(_latex_item(b) for b in exp.get("bullets", []))
                lines.append(r"      \resumeItemListEnd")
        lines.extend([r"\resumeSubHeadingListEnd", r"\vspace{-5.5mm}", ""])

    if internships:
        lines.extend([r"\section{\textbf{Internships}}", r"\resumeSubHeadingListStart"])
        for exp in internships:
            lines.extend([r"    \resumeSubheading", f"      {{{_latex_escape(exp.get('title', 'Internship'))}}}{{{_latex_escape(exp.get('location', ''))}}}", f"      {{{_latex_escape(exp.get('company', 'Organization'))}}}{{{_latex_escape(exp.get('duration', ''))}}}"])
            if exp.get("bullets"):
                lines.append(r"      \resumeItemListStart")
                lines.extend(_latex_item(b) for b in exp.get("bullets", []))
                lines.append(r"      \resumeItemListEnd")
        lines.extend([r"\resumeSubHeadingListEnd", r"\vspace{-5.5mm}", ""])

    skill_lines: List[str] = []
    if isinstance(skills, dict):
        for label, items in skills.items():
            clean = _clean_list(items)
            if clean:
                skill_lines.append(f"     \\textbf{{{_latex_escape(label.title())}}}{{: {_latex_escape(', '.join(clean))}}} {NL}")
    else:
        clean = _clean_list(skills)
        if clean:
            skill_lines.append(f"     \\textbf{{Skills}}{{: {_latex_escape(', '.join(clean))}}} {NL}")
    if skill_lines:
        lines.extend([r"\section{\textbf{Technical Skills and Interests}}", r" \begin{itemize}[leftmargin=0.05in, label={}]", r"    \small{\item{"])
        lines.extend(skill_lines)
        lines.extend([r"    }}", r" \end{itemize}", r" \vspace{-16pt}", ""])

    if certifications:
        lines.extend([r"\section{\textbf{Certifications}}", r"\resumeSubHeadingListStart"])
        for cert in certifications:
            lines.extend([r"\resumePOR", f"    {{{_latex_escape(cert.get('name', 'Certification'))}}}", f"    {{{_latex_escape(cert.get('issuer', ''))}}}", f"    {{{_latex_escape(cert.get('year', ''))}}}"])
        lines.extend([r"\resumeSubHeadingListEnd", r"\vspace{-5mm}", ""])

    if achievements:
        lines.extend([r"\section{\textbf{Achievements}}", r"\resumeSubHeadingListStart"])
        for ach in achievements:
            lines.extend([r"\resumePOR", f"    {{{_latex_escape(str(ach))}}}{{}}{{}}"])
        lines.extend([r"\resumeSubHeadingListEnd", r"\vspace{-5mm}", ""])

    if publications:
        lines.extend([r"\section{\textbf{Publications}}", r"\resumeSubHeadingListStart"])
        for pub in publications:
            if isinstance(pub, dict):
                title = pub.get("title", "Publication")
                desc = f"{pub.get('journal', '')} ({pub.get('year', '')})".strip()
                lines.extend([r"\resumePOR", f"    {{{_latex_escape(title)}}}{{{_latex_escape(desc)}}}{{}}"])
            else:
                lines.extend([r"\resumePOR", f"    {{{_latex_escape(str(pub))}}}{{}}{{}}"])
        lines.extend([r"\resumeSubHeadingListEnd", r"\vspace{-5mm}", ""])

    lines.extend([r"\end{document}", ""])
    return "\n".join(lines).encode("utf-8")
